# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "bg-img-with-overlay"
  description: A background image with centered overlay image
  icon: web_asset
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: bookshop:bg-img-with-overlay
  description: A background image with centered overlay image
  background_image:
    image_path: 
    image_alt: 
  logo_image:
    image_path: 
    image_alt: 
    
    

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
